# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trandemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Trandemo

  target 'TrandemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrandemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Masonry'
  pod 'SDWebImage', '~>3.8'
  pod 'AFNetworking'
  # 与H5 交互
   pod 'WebViewJavascriptBridge'
   pod 'Toast'
   pod 'MJRefresh'
   
   pod 'CYLTabBarController','~> 1.17.4'
   pod 'YYKit'
   pod 'MJExtension'
end
